version: "3.9"
services:

  gtm-mysql:
    image: mysql:8.0
    restart: always
    container_name: gtm-mysql
    env_file: "./mysql/local/mysql.env"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/local/db_data:/var/lib/mysql
      - ./mysql/local/my.cnf:/etc/mysql/my.cnf
    networks:
      - gtm-network

  gtm-server:
    image: nginx:1.22.1-alpine
    restart: unless-stopped
    tty: true
    container_name: gtm-server
    ports:
      - "8005:80"
    depends_on:
      - gtm-app
      - gtm-mysql
    volumes:
      - ./app/source:/var/www
      - ./nginx/local/local.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - gtm-network

  gtm-app:
    build:
      args:
        user: www
        uid: 1001
      context: ./app
      dockerfile: app.Dockerfile
    container_name: gtm-app
    image: gtm-app:latest
    restart: unless-stopped
    tty: true
    env_file: "./app/source/.env.local"
    environment:
      CONTAINER_ROLE: app
    working_dir: /var/www
    volumes:
      - ./app/source:/var/www
      - ./php/local/php.local.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - gtm-mysql
    networks:
      - gtm-network

  gtm-queue:
    image: gtm-app:latest
    restart: always
    container_name: gtm-queue
    depends_on:
      - gtm-app
      - gtm-mysql
    environment:
      CONTAINER_ROLE: queue
    volumes:
      - ./app/source:/var/www
    env_file: "./app/source/.env.local"
    networks:
      - gtm-network

#  #Phpmyadmin Service
#  gtm-phpmyadmin:
#    image: phpmyadmin/phpmyadmin:5.2.1
#    container_name: gtm-phpmyadmin
#    depends_on:
#      - gtm-mysql
#    tty: true
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      PMA_ARBITRARY: 1
#    ports:
#      - "8085:8085"
#    networks:
#      - gtm-network

  gtm-node:
    build:
      args:
        user: www
        uid: 1001
      context: ./app
      dockerfile: node.Dockerfile
    container_name: gtm-node
    working_dir: /var/www
    env_file: "./app/source/.env.local"
    ports:
      - "3016:3000"
    volumes:
      - ./app/source:/var/www
    networks:
      - gtm-network

#Docker Networks
networks:
  gtm-network:
    driver: bridge
